export type rpgStylesType =
  | 'Fantasia'
  | 'Fantasia Heróica'
  | 'Ninja vs Samurai'
  | 'Espada e Feitiçaria'
  | 'Fantasia Épica'
  | 'Fantasia Mística'
  | 'Fantasia Sombria'
  | 'Intriga'
  | 'Guerra'
  | 'Nave Mãe'
